# Generated by Django 4.2.30 on 2026-07-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuzzArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=500, unique=True)),
                ('topic', models.CharField(choices=[('transfers', 'Transfer News'), ('preseason', 'Pre-Season Friendlies'), ('wc2030', '2030 World Cup Watch'), ('aftermath', 'Post-WC Fallout')], max_length=20)),
                ('headline', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['topic', '-published_at'], name='football_bu_topic_bfa989_idx')],
            },
        ),
    ]
